<?php
/**
 * @var $this Wsu_AdminTheme_Block_Adminhtml_System_Config_Fieldset_Hint
 */
?>
<div class="box">
    <div style="background:url('#') no-repeat left center;padding-left:55px;min-height:42px;">
        <a href="#" target="_blank" style="float:right;">
            <img src="#" alt="Fork me on GitHub" title="Fork me on GitHub" />
        </a>
        <h4><?php echo $this->helper('wsu_admintheme')->__('Wsu AdminTheme allows you to change the theme of Magento Admin Panel.'); ?></h4>
        <p style="margin-bottom:0;"><?php echo $this->helper('wsu_admintheme')->__('Full overview available'); ?> <a href="<?php echo $this->escapeHtml($this->helper('wsu_admintheme')->__('#')); ?>" target="_blank"><?php echo $this->helper('wsu_admintheme')->__('here'); ?></a>.</p>
    </div>
</div>