<?php

	$config_logo=Mage::getStoreConfig('wsu_admintheme/config/logo');
	if($config_logo==""){
		$config_path = Mage::getBaseUrl('skin').'adminhtml/default/go/images/logo.gif';
	}else{
		$config_path = Mage::getBaseUrl('media').'theme/'.$config_logo;
	}


	$loginBk_img=Mage::getStoreConfig('wsu_admintheme/config/login_bk');
	if($loginBk_img==""){
		$loginBk_path = Mage::getBaseUrl('skin').'adminhtml/default/go/images/bkg_login.jpg';
	}else{
		$loginBk_path = Mage::getBaseUrl('media').'theme/admin/'.$loginBk_img;
	}


	$enableRequest = Mage::getStoreConfig('wsu_networksecurities/genadmin_settings/request_admin_enabled');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?=Mage::helper('adminhtml')->__('Log into Magento Admin Page') ?></title>
    <link type="text/css" rel="stylesheet" href="<?=$this->getSkinUrl('reset.css') ?>" media="all" />
    <link type="text/css" rel="stylesheet" href="<?=$this->getSkinUrl('boxes.css') ?>" media="all" />
    <link rel="icon" href="<?=$this->getSkinUrl('favicon.ico')  ?>" type="image/x-icon" />
    <link rel="shortcut icon" href="<?=$this->getSkinUrl('favicon.ico') ?>" type="image/x-icon" />
	
	<link rel="stylesheet" type="text/css" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.min.css"/>
	<link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css"/>
		
	<script type="text/javascript" src="//code.jquery.com/jquery-1.11.1.min.js"></script> 
	<script type="text/javascript">if(!window.jQuery){ document.write(unescape("%3Cscript src='<?=$this->getJsUrl('jquery-1.11.1.min.js') ?>' type='text/javascript'%3E%3C/script%3E")); }</script>
	
	<script type="text/javascript" src="//code.jquery.com/ui/1.10.4/jquery-ui.min.js"></script> 
	<script type="text/javascript">if(!window.jQuery){document.write(unescape("%3Cscript src='<?=$this->getJsUrl('jquery-ui.min.1.10.4.js') ?>' type='text/javascript'%3E%3C/script%3E"));}</script>
	
	<script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script> 
	<script type="text/javascript">
		if(!window.jQuery){
			document.write(unescape("%3Cscript src='<?=$this->getJsUrl('jquery-migrate-1.2.1.min.js') ?>' type='text/javascript'%3E%3C/script%3E"));
		}</script>
	
	<script type="text/javascript" src="<?=$this->getJsUrl('noConflict.js') ?>"></script> 
    <script type="text/javascript" src="<?=$this->getJsUrl('prototype/prototype.js') ?>"></script>
    <script type="text/javascript" src="<?=$this->getJsUrl('prototype/validation.js') ?>"></script>
    <script type="text/javascript" src="<?=$this->getJsUrl('scriptaculous/effects.js') ?>"></script>
    <script type="text/javascript" src="<?=$this->getJsUrl('mage/adminhtml/form.js') ?>"></script>
    <script type="text/javascript" src="<?=$this->getJsUrl('mage/captcha.js') ?>"></script>
	<script type="text/javascript" src="<?=$this->getJsUrl('wsu/networksecurities/networksecurities.js') ?>"></script>

    <!--[if IE]> <link rel="stylesheet" href="<?=$this->getSkinUrl('iestyles.css') ?>" type="text/css" media="all" /> <![endif]-->
    <!--[if lt IE 7]> <link rel="stylesheet" href="<?=$this->getSkinUrl('below_ie7.css') ?>" type="text/css" media="all" /> <![endif]-->
    <!--[if IE 7]> <link rel="stylesheet" href="<?=$this->getSkinUrl('ie7.css') ?>" type="text/css" media="all" /> <![endif]-->
</head>
<body id="page-login" onload="document.forms.loginForm.username.focus();" style="background-image:url(<?=$loginBk_path?>);">
<div class="login-container">
    <div class="login-box">
        <form method="post" action="" id="loginForm" class="humanize">
            <div class="login-form">
                <input name="form_key" type="hidden" value="<?=$this->getFormKey() ?>" />
                <h2 style="background:url(<?=$config_path?>) no-repeat 13px 10px;background-size:auto 65px;"><?=Mage::helper('adminhtml')->__('Log in to Admin Panel') ?></h2>
                <div id="messages">
                    <?=$this->getMessagesBlock()->getGroupedHtml() ?>
                </div>
                <div class="input-box input-left"><label for="username"><?=Mage::helper('adminhtml')->__('User Name:') ?></label><br/>
                    <input type="text" id="username" name="login[username]" value="" class="required-entry input-text" /></div>
                <div class="input-box input-right"><label for="login"><?=Mage::helper('adminhtml')->__('Password:') ?></label><br />
                    <input type="password" id="login" name="login[password]" class="required-entry input-text" value="" /></div>
                <?=$this->getChildHtml('form.additional.info'); ?>
                <div class="clear"></div>
                <div class="form-buttons">
                    <a class="left" href="<?=Mage::helper('adminhtml')->getUrl('adminhtml/index/forgotpassword', array('_nosecret' => true)) ?>"><?=Mage::helper('adminhtml')->__('Forgot your password?') ?></a>
                    <input type="submit" class="form-button" value="<?=Mage::helper('adminhtml')->__('Login') ?>" title="<?=Mage::helper('adminhtml')->__('Login') ?>" /></div>
            </div>
        </form>
		<div class="login-support">
			<?php if($enableRequest): ?>
				 <form action="<?=Mage::helper('adminhtml')->getUrl('adminhtml/wsu/requestaccess/', array('_nosecret' => true)) ?>" method="post" enctype="multipart/form-data" class="humanize">
					<p>Need to get your own store? <input type="submit" value="Make a Request"  class="button"/></p>
				 </form>
			 <?php else: ?>
				 
			 <?php endif; ?>
		</div>
		 <p id="ip"><?=Mage::helper('wsu_networksecurities')->get_ip_address()?></p>
            <p class="legal"><?=Mage::helper('adminhtml')->__('Magento is a trademark of Magento Inc. Copyright &copy; %s Magento Inc.', date('Y')) ?></p>
        <div class="bottom"></div>
        <script type="text/javascript">
            var loginForm = new varienForm('loginForm');
        </script>
    </div>
</div>
</body>
</html>

