<?php $_processes = $this->getProcessesForReindex()?>
<?php if ($_processes) :?>
<div class="notification-global">
    <i class="fa fa-exclamation-triangle"></i><strong><?php echo $this->helper('index')->__('One or more of the Indexes are not up to date:') ?></strong>
    <?php echo implode(', ', $_processes)?>.
    <?php echo $this->helper('index')->__('Click here to go to <a href="%s">Index Management</a> and rebuild required indexes.', $this->getManageUrl());?>
</div>
<?php endif;?>
